"""
Push PFW seed photos to F0 (AT-M140) and trigger media scan, with registration
verification built in.

Sources:
  - Photos: output/pfwseed_photos/PFWSEED_*.jpg  (generated by gen_pfwseed_photos.py)

Target on device: /sdcard/DCIM/PFWSEED_C11/

Reused pattern: scripts/setup_gallery_media.py (adb helper, ensure_device,
push_dir, media_scan). Not modified — this variant pins -s SERIAL and adds
a MediaStore registration-count verification gate per
MEDIA_SEED_DESIGN_C11_GAP8_2026-07-02.md section 3/S1-2.
"""

from __future__ import annotations

import subprocess
import sys
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
PHOTO_DIR = PROJECT_ROOT / "output" / "pfwseed_photos"

SERIAL = "B06201249E0002F0"
DEVICE_DIR = "/sdcard/DCIM/PFWSEED_C11"

EXPECTED_COUNT = 5
VERIFY_RETRY_DELAY_S = 2


def adb(*args: str, check: bool = True) -> subprocess.CompletedProcess:
    cmd = ["adb", "-s", SERIAL, *args]
    return subprocess.run(cmd, check=check, capture_output=True, text=True)


def ensure_device() -> None:
    r = subprocess.run(["adb", "devices"], check=True, capture_output=True, text=True)
    lines = [l for l in r.stdout.splitlines() if l.strip() and "device" in l and "List of" not in l]
    if not lines:
        sys.exit("ERROR: no adb device attached")
    if len(lines) > 1:
        sys.exit(f"ERROR: multiple devices attached (expected sole {SERIAL}):\n{r.stdout}")
    serials = [l.split()[0] for l in lines]
    if SERIAL not in serials:
        sys.exit(f"ERROR: expected device {SERIAL} not found. Attached: {serials}")


def clear_device_dir() -> None:
    adb("shell", f"rm -rf {DEVICE_DIR}", check=False)
    adb("shell", f"mkdir -p {DEVICE_DIR}")


def push_dir(src: Path) -> int:
    if not src.exists():
        return 0
    files = sorted(p for p in src.iterdir() if p.is_file())
    if not files:
        return 0
    for f in files:
        adb("push", str(f), f"{DEVICE_DIR}/{f.name}")
    return len(files)


def media_scan() -> None:
    # Per-file broadcast. Works on API 29+; individual files registered with MediaStore.
    r = adb("shell", f"ls {DEVICE_DIR}")
    names = [n for n in r.stdout.splitlines() if n.strip()]
    for n in names:
        adb(
            "shell",
            "am", "broadcast",
            "-a", "android.intent.action.MEDIA_SCANNER_SCAN_FILE",
            "-d", f"file://{DEVICE_DIR}/{n}",
            check=False,
        )


def count_registered() -> int:
    r = adb(
        "shell",
        "content", "query",
        "--uri", "content://media/external/images/media",
        "--projection", "_display_name",
        check=False,
    )
    lines = [l for l in r.stdout.splitlines() if "PFWSEED" in l]
    return len(lines)


def verify_registered(expected: int) -> int:
    """Query MediaStore for PFWSEED rows; retry once after a short delay."""
    n = count_registered()
    if n == expected:
        return n
    time.sleep(VERIFY_RETRY_DELAY_S)
    return count_registered()


def main() -> int:
    ensure_device()
    clear_device_dir()
    n_photos = push_dir(PHOTO_DIR)
    media_scan()

    n_registered = verify_registered(EXPECTED_COUNT)
    if n_registered != EXPECTED_COUNT:
        print(f"ERROR: MediaStore registration mismatch — expected {EXPECTED_COUNT}, found {n_registered}")
        return 1

    print(f"Pushed {n_photos} photos -> {DEVICE_DIR}")
    print(f"MediaStore registration verified: {n_registered}/{EXPECTED_COUNT} PFWSEED entries")
    return 0


if __name__ == "__main__":
    sys.exit(main())
