"""
Push gallery TC preset media to ODIN2 and trigger media scan.

Sources:
  - Photos: output/gallery_photos/*.jpg  (generated by gen_gallery_photos.py)
  - Videos: output/gallery_videos/*.mp4  (user-captured; optional)

Target on device: /sdcard/DCIM/MyGallery_TC/
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
PHOTO_DIR = PROJECT_ROOT / "output" / "gallery_photos"
VIDEO_DIR = PROJECT_ROOT / "output" / "gallery_videos"

DEVICE_DIR = "/sdcard/DCIM/MyGallery_TC"


def adb(*args: str, check: bool = True) -> subprocess.CompletedProcess:
    cmd = ["adb", *args]
    return subprocess.run(cmd, check=check, capture_output=True, text=True)


def ensure_device() -> None:
    r = adb("devices")
    lines = [l for l in r.stdout.splitlines() if l.strip() and "device" in l and "List of" not in l]
    if not lines:
        sys.exit("ERROR: no adb device attached")
    if len(lines) > 1:
        sys.exit(f"ERROR: multiple devices attached:\n{r.stdout}")


def clear_device_dir() -> None:
    adb("shell", f"rm -rf {DEVICE_DIR}", check=False)
    adb("shell", f"mkdir -p {DEVICE_DIR}")


def push_dir(src: Path) -> int:
    if not src.exists():
        return 0
    files = sorted(p for p in src.iterdir() if p.is_file())
    if not files:
        return 0
    for f in files:
        adb("push", str(f), f"{DEVICE_DIR}/{f.name}")
    return len(files)


def media_scan() -> None:
    # Per-file broadcast. Works on API 29+; individual files registered with MediaStore.
    r = adb("shell", f"ls {DEVICE_DIR}")
    names = [n for n in r.stdout.splitlines() if n.strip()]
    for n in names:
        adb(
            "shell",
            "am", "broadcast",
            "-a", "android.intent.action.MEDIA_SCANNER_SCAN_FILE",
            "-d", f"file://{DEVICE_DIR}/{n}",
            check=False,
        )


def main() -> int:
    ensure_device()
    clear_device_dir()
    n_photos = push_dir(PHOTO_DIR)
    n_videos = push_dir(VIDEO_DIR)
    media_scan()
    print(f"Pushed {n_photos} photos + {n_videos} videos -> {DEVICE_DIR}")
    print("Media scan broadcast sent. Re-open 마이 갤러리 to see the preset.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
